# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginAvvocato.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(399, 300)
        Form.setStyleSheet("background-color: rgb(255, 240, 186);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 30, 161, 41))
        self.label.setStyleSheet("font: 30pt \"Arial\";")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(140, 100, 241, 31))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 229);")
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 117, 16))
        self.label_2.setStyleSheet("font: 14pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(170, 200, 221, 20))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 230, 174, 32))
        self.pushButton.setStyleSheet("border-width: 2px;\n"
"border-color: black;\n"
"font: bold 14px;\n"
"min-width: 10em; \n"
"background-color: rgb(255, 255, 229);")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 91, 16))
        self.label_4.setStyleSheet("font: 14pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(140, 160, 241, 31))
        self.textEdit_3.setStyleSheet("\n"
"background-color: rgb(255, 255, 229);")
        self.textEdit_3.setObjectName("textEdit_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "LOGIN"))
        self.label_2.setText(_translate("Form", "CODICE FISCALE"))
        self.label_5.setText(_translate("Form", "codice fiscale e/o password errata! "))
        self.pushButton.setText(_translate("Form", "ACCEDI"))
        self.label_4.setText(_translate("Form", "PASSWORD"))
